name: Zig Codegen Tests

on:
  push:
    branches: [ main, feature, codegen ]
  pull_request:
    branches: [ main, feature, codegen ]
  workflow_dispatch:

jobs:
  test-codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: tests/CodeGen/Python-ONNX/requirements.txt

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/CodeGen/Python-ONNX/requirements.txt

      - name: Set up Zig 0.14.0
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0

      - name: Run Python ONNX code generator
        run: python3 tests/CodeGen/Python-ONNX/onnx_gen.py

      - name: Run Zig codegen tests generation
        run: zig build test-codegen-gen

      - name: Run Zig codegen tests with summary
        run: zig build test-codegen --summary all